version = 0.1
[default.deploy.parameters]
stack_name = "plant-based-pizza"
resolve_s3 = true
s3_prefix = "plant-based-pizza"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
