version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017

  datadog-agent:
    image: datadog/agent
    pid: host
    ports:
      - "8126:8126"
      - "4317:4317"
      - "4318:4318"
    environment:
      - DD_ENV=test
      - DD_SITE=datadoghq.eu
      - DD_SERVICE=OrdersService
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED="true"
      - DD_APM_NON_LOCAL_TRAFFIC="true"
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC="true"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  
  cache:
    image: redis:7.2
    ports:
      - '6379:6379'

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - 8443:8080
    volumes:
      - ./mocks/loyalty-api:/home/wiremock

  gripmock:
    image: tkpd/gripmock:latest
    ports:
      - 4770:4770
      - 4771:4771
    volumes:
      - ./mocks/grpc-mocks:/proto
    command: --stub=/proto/stubs /proto/loyalty.proto /proto/payment.proto