version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 27017
  
  cache:
    image: redis:7.2
    ports:
      - "6379:6379"

  wiremock:
    image: wiremock/wiremock:latest
    expose:
      - 8080
    volumes:
      - ./mocks/loyalty-api:/home/wiremock

  gripmock:
    image: tkpd/gripmock:latest
    expose:
      - 4770
      - 4771
    volumes:
      - ./mocks/grpc-mocks:/proto
    command: --stub=/proto/stubs /proto/loyalty.proto /proto/payment.proto

  datadog-agent:
    image: datadog/agent
    pid: host
    expose:
      - 4317
      - 4318
    environment:
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT-0.0.0.0:4318
      - DD_ENV=test
      - DD_SITE=datadoghq.eu
      - DD_SERVICE=OrdersService
      - DD_API_KEY=${DD_API_KEY}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  local.orders-api:
    image: ${REGISTRY}/orders-api:${IMAGE_TAG}
    depends_on:
      - cache
    restart: on-failure
    ports:
      - "5004:8080"
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OtlpEndpoint=http://datadog-agent:4317
      - Environment=local
      - RedisConnectionString=cache
      - Services__Loyalty=http://wiremock:8443
      - Services__LoyaltyInternal=http://gripmock:4770
      - Services__PaymentInternal=http://gripmock:4770
      - Services__Recipes=http://wiremock:8443
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=OrdersApi
      - ServiceDiscovery__ConsulServiceEndpoint=
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'
      - Auth__PaymentApiKey=the api key to use, use a secret store in production
      - AWS_REGION=eu-west-1
      - SERVICE_NAME=OrdersService
      - BUILD_VERSION=${IMAGE_TAG}

  local.orders-worker:
    image: ${REGISTRY}/orders-worker:${IMAGE_TAG}
    depends_on:
      - cache
    restart: on-failure
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OtlpEndpoint=http://datadog-agent:4317
      - RedisConnectionString=cache
      - Services__Loyalty=http://wiremock:8080
      - Services__LoyaltyInternal=http://gripmock:4770
      - Services__PaymentInternal=http://gripmock:4770
      - Services__Recipes=http://wiremock:8080
      - Environment=local
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=OrdersWorker
      - ServiceDiscovery__ConsulServiceEndpoint=
      - Messaging__BusName=dev.orders
      - AWS_REGION=eu-west-1
      - SERVICE_NAME=OrdersService
      - BUILD_VERSION=${IMAGE_TAG}
      - QueueConfiguration__OrderQualityCheckedQueueUrl=OrderQualityCheckedQueue
      - QueueConfiguration__LoyaltyPointsUpdatedQueueUrl=LoyaltyUpdatedQueue