version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: recipes-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 4317:4317
      - 4318:4318

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - 8443:8080
    volumes:
      - ./mocks/recipe-api:/home/wiremock

  local.recipe-api:
    image: ${REGISTRY}/recipe-api:${IMAGE_TAG}
    ports:
      - "5138:8080"
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OtlpEndpoint=http://jaeger:4317
      - Environment=local
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=
      - ServiceDiscovery__ConsulServiceEndpoint=http://consul:8500
      - Messaging__BusName=dev.recipes
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'
      - AWS_REGION=eu-west-1