version: "3.7"
services:

  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 27017

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    expose:
      - 16686
      - 13133
      - 4317
      - 4318
  
  cache:
    image: redis:7.2
    ports:
      - "6379:6379"

  wiremock:
    image: wiremock/wiremock:latest
    expose:
      - 8080
    volumes:
      - ./mocks/recipe-api:/home/wiremock

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping

  local.kitchen-api:
    image: ${REGISTRY}/kitchen-api:${IMAGE_TAG}
    ports:
      - "5097:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - DatabaseConnection=mongodb://mongodb:27017 
      - OtlpEndpoint=http://jaeger:4317
      - Environment=local
      - RedisConnectionString=cache
      - Services__Recipes=http://wiremock:8080
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=
      - ServiceDiscovery__ConsulServiceEndpoint=http://consul:8500
      - Messaging__HostName=rabbitmq
      - Messaging__ExchangeName=dev.kitchen
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'

  local.kitchen-worker:
    image: ${REGISTRY}/kitchen-worker:${IMAGE_TAG}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OtlpEndpoint=http://jaeger:4317
      - Environment=local
      - RedisConnectionString=cache
      - Services__Recipes=http://wiremock:8080
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=
      - ServiceDiscovery__ConsulServiceEndpoint=http://consul:8500
      - Messaging__HostName=rabbitmq
      - Messaging__ExchangeName=dev.kitchen