version: "3.7"
services:

  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 27017
  
  cache:
    image: redis:7.2
    ports:
      - "6379:6379"

  wiremock:
    image: wiremock/wiremock:latest
    expose:
      - 8080
    volumes:
      - ./mocks/recipe-api:/home/wiremock

  datadog-agent:
    image: datadog/agent
    pid: host
    expose:
      - 4317
      - 4318
    environment:
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT-0.0.0.0:4318
      - DD_ENV=${IMAGE_TAG}
      - DD_SITE=datadoghq.eu
      - DD_SERVICE=KitchenService
      - DD_API_KEY=${DD_API_KEY}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  local.kitchen-api:
    image: ${REGISTRY}/kitchen-api:${IMAGE_TAG}
    ports:
      - "5097:8080"
    restart: on-failure
    environment:
      - DatabaseConnection=mongodb://mongodb:27017 
      - OtlpEndpoint=http://jaeger:4317
      - Environment=local
      - RedisConnectionString=cache
      - Services__Recipes=http://wiremock:8080
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=KitchenApi
      - ServiceDiscovery__ConsulServiceEndpoint=
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'
      - Messaging__BusName=dev.kitchen
      - AWS_REGION=eu-west-1
      - SERVICE_NAME=KitchenService
      - BUILD_VERSION=${IMAGE_TAG}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

  local.kitchen-worker:
    image: ${REGISTRY}/kitchen-worker:${IMAGE_TAG}
    restart: on-failure
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OtlpEndpoint=http://jaeger:4317
      - Environment=local
      - RedisConnectionString=cache
      - Services__Recipes=http://wiremock:8080
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=KitchenWorker
      - ServiceDiscovery__ConsulServiceEndpoint=
      - Messaging__BusName=dev.kitchen
      - AWS_REGION=eu-west-1
      - SERVICE_NAME=KitchenService
      - BUILD_VERSION=${IMAGE_TAG}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}