name: Payment API CICD

on:
    push:
      branches:
        - microservices-module-6
      paths:
        - './.github/workflows/build-and-push-base.yaml'
        - './.github/workflows/build-payment-services.yaml'
        - './src/PlantBasedPizza.Payments/*'
        - './src/shared/*'
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@microservices-module-6
    with:
      image-name: payment-api
      dockerfile: src/PlantBasedPizza.Payments/application/PlantBasedPizza.Payments/Dockerfile-x86
      integration-test-compose-file: src/PlantBasedPizza.Payments/docker-compose-integration.yml
      integration-test-folder: src/PlantBasedPizza.Payments/tests/PlantBasedPizza.Payments.IntegrationTests
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      ecr-registry: ${{secrets.ECR_REGISTRY}}
        