name: Payment API CICD

on:
    push:
      branches:
        - microservices-module-6
    workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: payment-api:latest
          context: ./src
          file: src/PlantBasedPizza.Payments/application/PlantBasedPizza.Payments/Dockerfile