name: Recipe API CICD

on:
    push:
      branches:
        - main
        - feature/aws-serverless
        - feature/aws-serverless-datadog
      paths:
        - .github/workflows/build-base-java.yaml
        - .github/workflows/build-recipe-services.yaml
        - src/PlantBasedPizza.Recipes.Java/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-base-java.yaml@feature/aws-serverless-datadog
    with:
      service-name: "RecipeJavaApi"
      project-root: src/PlantBasedPizza.Recipes.Java
      image-name: recipe-api-java
      dockerfile: src/PlantBasedPizza.Recipes.Java/Dockerfile
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      ecr-registry: ${{secrets.ECR_REGISTRY}}
      dd_api_key: ${{secrets.DD_API_KEY}}
      dd_app_key: ${{secrets.DD_APP_KEY}}
  # integration-test:
  #   uses: jeastham1993/PlantBasedPizza/.github/workflows/integration-test-base.yaml@feature/aws-serverless
  #   needs: build-image
  #   with:
  #     service-name: "RecipeApi"
  #     integration-test-compose-file: src/PlantBasedPizza.Recipes/docker-compose-integration.yml
  #     integration-test-folder: src/PlantBasedPizza.Recipes/tests/PlantBasedPizza.Recipes.IntegrationTests
  #   secrets:
  #     deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
  #     ecr-registry: ${{secrets.ECR_REGISTRY}}
  #     dd_api_key: ${{secrets.DD_API_KEY}}
  # deploy-to-dev:
  #   uses: jeastham1993/PlantBasedPizza/.github/workflows/cdk-deploy-base.yaml@feature/aws-serverless
  #   needs: integration-test
  #   concurrency:
  #     group: recipes-dev-deploy
  #     cancel-in-progress: false
  #   with:
  #     cdk-folder: "src/PlantBasedPizza.Recipes/infra"
  #     environment: "dev"
  #   secrets:
  #     deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
  #     dd-api-key: ${{secrets.DD_API_KEY}}