name: Recipe API CICD

on:
    push:
      branches:
        - microservices-module-6
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-recipe-services.yaml
        - src/PlantBasedPizza.Recipes/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@microservices-module-6
    with:
      image-name: recipes-api
      dockerfile: src/PlantBasedPizza.Recipes/applications/PlantBasedPizza.Recipes.Api/Dockerfile-x86
      integration-test-compose-file: src/PlantBasedPizza.Recipes/docker-compose-integration.yml
      integration-test-folder: src/PlantBasedPizza.Recipes/tests/PlantBasedPizza.Recipes.IntegrationTests
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      ecr-registry: ${{secrets.ECR_REGISTRY}}
        