name: Payment API CICD

on:
    push:
      branches:
        - microservices-module-6
    workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: payment-api:latest
          context: ./src
          file: src/PlantBasedPizza.Payments/application/PlantBasedPizza.Payments/Dockerfile
      - name: docker-compose up
        run: docker-compose -f src/PlantBasedPizza.Payments/docker-compose-integration.yml up -d
      - name: Wait for docker to start
        run: sleep 5
      - name: Run Integration Tests
        run: dotnet test src/PlantBasedPizza.Payments/tests/PlantBasedPizza.Payments.IntegrationTests
          