name: Payment API CICD

on:
    push:
      branches:
        - microservices-module-6
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-payment-services.yaml
        - src/PlantBasedPizza.Payments/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-base.yaml@microservices-module-6
    with:
      unit-test-folder: src/PlantBasedPizza.Payments/tests/PlantBasedPizza.Payments.UnitTests
      image-name: payment-api
      dockerfile: src/PlantBasedPizza.Payments/application/PlantBasedPizza.Payments/Dockerfile-x86
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      ecr-registry: ${{secrets.ECR_REGISTRY}}
  integration-test:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/integration-test-base.yaml@microservices-module-6
    needs: build-image
    with:
      integration-test-compose-file: src/PlantBasedPizza.Payments/docker-compose-integration.yml
      integration-test-folder: src/PlantBasedPizza.Payments/tests/PlantBasedPizza.Payments.IntegrationTests
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}