on:
  workflow_call:
    inputs:
      image-name:
          required: true
          type: string
      dockerfile:
          required: true
          type: string
      integration-test-compose-file:
          required: true
          type: string
      integration-test-folder:
          required: true
          type: string

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: eu-west-1
            role-to-assume: ${{secrets.DEV_ACCOUNT_ROLE}}
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: ${{ inputs.image-name }}:latest
          context: ./src
          file: ${{ inputs.dockerfile }}
      - name: docker-compose up
        run: docker-compose -f ${{ inputs.integration-test-compose-file }} up -d
      - name: Wait for docker to start
        run: sleep 5
      - name: Run Integration Tests
        run: dotnet test ${{ inputs.integration-test-folder }}
      - name: Teardown
        run: docker-compose -f ${{ inputs.integration-test-compose-file }} down
      - name: Tag With Commit Hash
        run: docker tag ${{inputs.image-name}} ${{secrets.ECR_REGISTRY}}/${{inputs.image-name}}:${{ env.sha_short }}
      - uses: aws-actions/amazon-ecr-login@v2
        name: Login to Amazon ECR
        id: login-ecr
      - name: Tag With Commit Hash
        run: docker push ${{secrets.ECR_REGISTRY}}/${{inputs.image-name}}:${{ env.sha_short }}
          