name: Payment API CICD

on:
    push:
      branches:
        - main
        - feature/aws-serverless
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-payment-services.yaml
        - src/PlantBasedPizza.Payments/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read 

jobs:
  integration-test:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/integration-test-base.yaml@feature/aws-serverless
    with:
      integration-test-compose-file: src/PlantBasedPizza.Payments/docker-compose-integration.yml
      integration-test-folder: src/PlantBasedPizza.Payments/tests/PlantBasedPizza.Payments.IntegrationTests
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      ecr-registry: ${{secrets.ECR_REGISTRY}}

  deploy-to-dev:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/cdk-deploy-base.yaml@feature/aws-serverless
    needs: integration-test
    concurrency:
      group: payments-dev-deploy
      cancel-in-progress: false
    with:
      cdk-folder: "src/PlantBasedPizza.Payments/infra"
      environment: "dev"
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      dd-api-key: ${{secrets.DD_API_KEY}}