name: Deploy Shared Services

on:
    push:
      branches:
        - main
      paths:
        - shared-infrastructure/*
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/cdk-deploy-base.yaml@main
    with:
      cdk-folder: "shared-infrastructure"
      environment: "dev"
    secrets:
      deploy-role-arn: ${{secrets.DEPLOYMENT_ROLE_NAME}}
      dd_api_key: ${{secrets.DD_API_KEY}}