name: Integration Test Base Workflow

on:
  workflow_call:
    inputs:
      service-name:
          required: true
          type: string
      integration-test-compose-file:
          required: true
          type: string
      integration-test-folder:
          required: true
          type: string
    secrets:
      deploy-role-arn:
        description: 'The role for the AWS IAM role to use for deployment'
        required: true
      ecr-registry:
          required: true
      dd_api_key:
          required: true

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Install DD trace
        run: dotnet tool update -g dd-trace
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{secrets.deploy-role-arn}}
          role-session-name: GitHubActionsSession
      - uses: aws-actions/amazon-ecr-login@v2
        name: Login to Amazon ECR
        id: login-ecr
      - name:
        run: |
          echo "REGISTRY=${{secrets.ecr-registry}}" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: docker-compose up
        run: docker-compose -f ${{ inputs.integration-test-compose-file }} up -d
      - name: Wait for docker to start - 20s
        run: sleep 20
      - name: Run Integration Tests
        env:
          DD_CIVISIBILITY_AGENTLESS_ENABLED: true
          DD_API_KEY: ${{secrets.dd_api_key}}
          DD_SITE: datadoghq.eu
        run: dd-trace ci run --dd-service=${{inputs.service-name}} --dd-env=ci -- dotnet test ${{ inputs.integration-test-folder }}
      - name: Teardown
        run: docker-compose -f ${{ inputs.integration-test-compose-file }} down
          